#!/bin/sh

# git post-update hook to update www dir(s) on git push
# argv has a variable number of parameters, each of which is the name of ref
# that was actually updated

updir=/homes/isao/mojitos #git clones to update here
reponame=$(basename $(pwd) .git) #<reponame>

gitupweb()
{
	refname=$1 #e.g. refs/heads/master
	branch=$(basename $refname) #e.g. master
	docroot=$updir/$reponame-$branch

	{
		if [[ -d $docroot ]] && [[ -d $docroot/.git ]]
		then
			echo "*update $docroot"
			set -x
			cd "$docroot"
			unset GIT_DIR
			git pull --quiet
			git update-server-info
			chmod -R --changes a+rX ./* # macosx use -v -v instead of --changes
		else
			echo "!$docroot is not a git directory, doing nothing"
		fi
	} 2>&1 | logger
}

#main
for refname in "$@"
do
	logger "*$0 -> $refname"
	gitupweb $refname
done
exit 0
