#!/bin/bash
# http://ariya.ofilabs.com/2012/10/javascript-validator-with-esprima.html
#
# added checks for
#  - esvalidate is in $PATH
#  - file was not removed

which esvalidate >/dev/null || exit 0

for file in $(git diff-index --name-only --diff-filter=ACM HEAD | egrep '\.js$')
do
    esvalidate $file || {
        echo "Syntax error: $file"
        exit 1
    }
    echo "$status $file -> esvalidate ok"
done
