#!/bin/bash
# http://ariya.ofilabs.com/2012/10/javascript-validator-with-esprima.html
#
# added checks for
#  - esvalidate is in $PATH
#  - file was not removed

which esvalidate >/dev/null || exit 0

git diff-index --name-status HEAD | egrep '\.js$' | while read status file
do
    if [[ ! $status =~ ^D ]]
    then
        esvalidate $file || {
            echo "Syntax error: $file"
            exit 1
        }
        echo "$status $file -> esvalidate ok"
    fi
done
