#!/bin/sh -eu

# This script is for doing things before a laptop goes to sleep, and on
# awakening. It's not useful for a workstation as-is.
#
# To use, first install these tools from download/source or homebrew:
# 1. sleepwatcher <http://www.bernhard-baehr.de/>
# 2. blueutil <http://www.frederikseiffert.de/blueutil/>
#
# Then symlink both ~/.sleep and ~/.wakeup to this script, so it's invoked
# by the homebrew default LaunchAgent config for "sleepwatcher", which is:
#   /usr/local/sbin/sleepwatcher -V -s ~/.sleep -w ~/.wakeup


#
# vars
#

# full path because launchd doesn't include /usr/local/bin in it's $PATH
blueutil=/usr/local/bin/blueutil

# prefix logged lines for grepping (logs to /var/log/system/log)
tag="dot-wakeup:$(basename $0)"


#
# checks
#

if [[ ! -x $blueutil ]]
then
    log 'Required tool $blueutil was not found.'
    log 'Install it via homebrew, or <http://www.frederikseiffert.de/blueutil/>'
    exit 1
fi


#
# functions
#

# log to both system.log and stderr
log()
{
    logger -t $tag -s "$1"
}

# bluetooth "on" or "off"
bluetooth_status()
{
    if [[ $($blueutil status) =~ (on|off)$ ]]
    then
        echo ${BASH_REMATCH[1]}
    else
        log 'oh geez. cannot get bluetooth status.'
        exit 3
    fi
}

# check for external monitor(s)
have_external_monitor()
{
    # FIXME: system_profiler is veerrry slow
    system_profiler SPDisplaysDataType |\
        grep 'Display Serial Number:' &>/dev/null
    echo $?
}

# Turn bluetooth OFF if there is no external monitor attached. Unless
# there is an external monitor, I don't want my laptop attempting to
# connect to the bluetooth keyboard and trackpad, which will drain battery
bluetooth_OFF_unless_monitor()
{
    if [[ $(bluetooth_status) == 'on' && ! $(have_external_monitor) ]]
    then
        log 'turning bluetooth OFF'
        $blueutil off &
    fi
}

# Turn bluetooth ON if it is currently off
bluetooth_ON()
{
    if [[ $(bluetooth_status) == 'off' ]]
    then
        log 'turning bluetooth ON'
        $blueutil on
    fi
}

# unmount all usb drives (ignores netwrok volumes and hard drives)
# unmount_usb_drives()
# {
#     system_profiler SPUSBDataType | grep 'Mount Point:' |\
#     while read ignore1 ignore2 mountpoint
#     do
#         log "unmounting $mountpoint"
#         diskutil unmount "$mountpoint" &
#     done
# }

# eject all ejectable attached drives
eject_every_disk()
{
    osascript -e 'tell application "Finder" to eject (every disk whose local volume is true)'
}


#
# main
#

if [[ $0 =~ \.sleep$ ]]
then
    log 'sleep tasks…'
    eject_every_disk
    bluetooth_ON

elif [[ $0 =~ \.wakeup$ ]]
then
    log 'wakeup tasks…'
    bluetooth_OFF_unless_monitor

fi

# execute this script file directly, i.e. `dot-wakeup` for test or debug stuff
#
# launchctl list de.bernhard-baehr.sleepwatcher
