#!/bin/bash
#
# Inspired by <https://github.com/gibfahn/dot/blob/main/link>
#
# shellcheck shell=bash disable=SC2059

set -eu

cd "$(dirname "$(readlink "$0")")/home"

source_basedir="$PWD"

echo "source_basedir: $source_basedir"

run_cmd='echo'


while read -r file
do
  # Remove leading "./"
  source_file="${file#./}"

  # Prefix with a dot.
  link_file=".${source_file}"
  link_dir="$(dirname "$link_file")"

  # If the source file is in a subdirectory, make the corresponding directory
  # if needed.
  if [[ "$(dirname "$source_file")" != '.' && ! -e "$HOME/$link_dir" ]]
  then
    $run_cmd mkdir -pv "$HOME/$link_dir"
  fi

  # `ln` flags:
  # -f force
  # -h treat directories like files       ????????
  # -i prompt before replacing anything
  # -s symbolic
  # -v verbose
  $run_cmd ln -fhisv "$source_basedir/$source_file" "$HOME/$link_file"

done < <(find . -type f -not \( -name '.*' -o -name '*-disabled' \))
